name: money
description: Money and Currency library for Dart.
version: 1.0.0
homepage: https://github.com/electricbolt/dart-money

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  decimal: ^1.2.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.17.3
